### PR TITLE
feat: Support attach command (#70)

### PR DESCRIPTION
**Pull request by mprey**
**Initial Draft**

Added:
- `slim attach [name]` command to auto-connect to the VM via an inline SSH client
- added `--attach` flag to `slim run` that will auto-connect once the VM is built
- added local storage that will remember the name of the last VM built to have an optional arg in `slim attach`

Notes:
- Where should the local storage be? Currently it is only storing in the directory slim is running from. Should it be in `~/.slim`?
- Should there be a health check (checking if the provider has the VM) before trying to connect to the VM?

### CODE REVIEW

**Comment by ssmirr** [comment]
Thanks for the PR @mprey! 

- I think it would be reasonable to add local storage to `~/.slim`, because the slim VMs don't have any relation to the cwd.

- I think the idea of health checks is interesting and could be useful for some other commands as well (ex. `slim vms`). But it might need to check/know state of the VM rather than just checking if it exists or not (VM could be `stopped`, `aborted`, etc)

**Comment by mprey** [comment]
Went ahead and moved the storage to the home directory.

I would love to help out implementing a more robust and general health check system. Do you think just a simple TCP ping to the VM would suffice? I think a separate PR outside of this would be necessary.

**Comment by ssmirr** [comment]
Great! A simple ping would be sufficient for now. 

And yes, we can have that as a separate PR before merging this one.

**Comment by mprey** [comment]
Had to force push after rebasing with the other PR, hopefully nothing is messed up. 

Added a simple health check before attaching.

**Pull request merged**
